platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'codeChallengeApp' do
    # Network
    pod 'Alamofire', '~> 4.6.0'

    # Image Download
    pod 'Kingfisher', '~> 4.10.1'
    
    # Database
    pod 'RealmSwift', '~> 3.7.4'
    
    # DI
    pod 'Swinject', '~> 2.5.0'
    
    # UI
    pod 'SnapKit', '~> 4.0.0'
    pod 'SVProgressHUD', '~> 2.2.5'
end