platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def test_pods
    # Network
    pod 'Alamofire', '~> 4.8.0'
    # Database
    pod 'RealmSwift', '~> 3.7.4'
    # DI
    pod 'Swinject', '~> 2.5.0'
end

target 'codeChallengeApp' do
    
    test_pods
    
    # Image Download
    pod 'Kingfisher', '~> 4.10.1'
    # UI
    pod 'SnapKit', '~> 4.0.0'
    pod 'SVProgressHUD', '~> 2.2.5'
end

target 'codeChallengeAppTests' do
    test_pods
end
